openapi: 3.0.3

info:
  title: API for endoscope
  description: API for endoscope
  contact:
    name: endoscope
    email: endoscope@localhost
  version: 1.0.0

tags:
  - name: directory
    description: directory API


paths:

  /directories:
    get:
      tags:
        - directories
      summary: Get directories
      description: Get directories
      operationId: getDirectories
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DirectoryEntity'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    put:
      tags:
        - directories
      summary: Create directory
      description: Create directory
      operationId: createDirectory
      requestBody:
        description: Directory to create
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DirectoryEntity'
        required: true
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /directories/subDirectories/{directoryId}:
    get:
      tags:
        - directories
      summary: Get sub directories
      description: Get sub directories
      operationId: getSubDirectories
      parameters:
        - name: directoryId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DirectoryEntity'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    put:
      tags:
        - directories
      summary: Create sub directory
      description: Create sub directory
      operationId: createSubDirectory
      parameters:
        - name: directoryId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Sub Directory to create
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DirectoryEntity'
        required: true
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

#############################
# Components                #
#############################

components:
  schemas:
    DirectoryEntity:
      type: object
      properties:
        directoryId:
          type: integer
          format: uuid
          description: The directory ID
        directoryName:
          type: string
          description: The directory name
        parentDirectory:
          type: integer
          description: The parent directory id
    InternalServerError:
      type: object
      properties:
        message:
          type: string
          description: The error message
        code:
          type: integer
          description: The error code